### PR TITLE
Add append testing functionality

### PR DESCRIPTION
**Pull request by peyrin**
Note: I haven't tested this yet. We should definitely make sure this works before merging it in

### CODE REVIEW

**Comment by conorgil** [comment]
Looks fine to me at first glance. I will write a test to make sure it works as expected.

**Comment by peyrin** [comment]
It might help to use existing code from fa20 project submissions and see if adding bandwidth tests to student submissions works (e.g. find a student who failed the bandwidth test and write a test and see if it fails)

**Comment by nicholasngai** [comment]
The API should probably match what we use in our injected userlib, right?

https://github.com/cs161-staff/project2-autograder/blob/master/userlib.go

Notably, `GetDataUsage() int` would be the public function.

**Comment by peyrin** [comment]
I changed it to bandwidth because DataUsage seems like an arbitrary term we made up and doesn't really sound like it's testing efficiency, imo. We could either change the staff-side userlib to use the variable bandwidth, or change the user-side userlib to use DataUsage. I'm fine with either

**Comment by conorgil** [comment]
The project spec discusses bandwidth, so I vote for changing terminology to match that.

**Comment by nicholasngai** [comment]
Agreed. We can merge this now and open up an issue against the autograder to use bandwidth terminology in the staff userlib.

**Comment by peyrin** [comment]
Has anyone tested that this works? If not, I'll download some submissions from fa20 and see if they check out

**Review by conorgil — APPROVED** [review]
Tests pass and looks good to me.

@peyrin This PR allows students to more easily check how much bandwidth they have used, but it does not give them an actual test to code against. I think we should merge this PR now and consider adding a bandwidth test for students to code against later.

**Comment by peyrin** [comment]
Agreed, we can include that in the "coding tips" part of the spec to minimize starter code updates

**Comment by conorgil** [comment]
> Has anyone tested that this works? If not, I'll download some submissions from fa20 and see if they check out

I have not tested it against previous solutions, but I wrote a basic test to verify that it does indeed calculate the bandwidth usage correctly for store/load.

**Comment by peyrin** [comment]
Basic test lgtm, I'll test it against previous solutions later. I think the basic test is enough to be reasonably confident this isn't broken

**Pull request merged**
